theme: jekyll-theme-cayman
title: Ghost
description: Ghost is a Destiny 2 player's best friend! Eventually, it will offer functions like creating tournament brackets based on assessed player skill and then assigning maps to each match based on the preferences of each player involved, as well as links to other great tools to use. For now, however, it's a giant WIP, and it's just crickets.
